name: Master RS Pipeline (After Split)

on:
  #workflow_run:
    #workflows: ["Split RS Stocks by Exchange"]   # ← Only this triggers the whole chain
    #types: [completed]
    #branches: [main]

  workflow_dispatch:

jobs:
  generate-ipo:
    uses: ./.github/workflows/4-generate-ipo-stocks.yml
    # needs: not required for the first one

  filter-52wh:
    needs: generate-ipo
    uses: ./.github/workflows/5-rs-52wh-filter.yml

  filter-52wl:
    needs: filter-52wh
    uses: ./.github/workflows/8-rs-52wl-filter.yml

  update-rs-thresholds:
    needs: filter-52wh
    uses: ./.github/workflows/6-RS-TV.yml
